theme: jekyll-theme-leap-day
remote_theme: pages-themes/leap-day@v0.2.0
description: PIV (FIPS 201) Non-Authoritative Manual
show_downloads: false
url: "https://pivmanual.openphysical.org"
include: 
  - _pages
titles_from_headings:
  enabled:     false
relative_links:
  enabled:     true
  collections: false
plugins:
  - jekyll-sitemap